# Generated by Django 5.1 on 2024-08-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Decimo',
            },
        ),
        migrations.CreateModel(
            name='DecimoPrimeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'DecimoPrimeiro',
            },
        ),
        migrations.CreateModel(
            name='DecimoSegundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'DecimoSegundo',
            },
        ),
        migrations.CreateModel(
            name='Nono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Nono',
            },
        ),
        migrations.CreateModel(
            name='Oitavo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Oitavo',
            },
        ),
        migrations.CreateModel(
            name='Primeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Primeiro',
            },
        ),
        migrations.CreateModel(
            name='Quarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merenda_manha', models.TextField(max_length=255)),
                ('almoco', models.TextField(max_length=255)),
                ('merenda_tarde', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Quarta',
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Quarto',
            },
        ),
        migrations.CreateModel(
            name='Quinta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merenda_manha', models.TextField(max_length=255)),
                ('almoco', models.TextField(max_length=255)),
                ('merenda_tarde', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Quinta',
            },
        ),
        migrations.CreateModel(
            name='Quinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Quinto',
            },
        ),
        migrations.CreateModel(
            name='Segunda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merenda_manha', models.TextField(max_length=255)),
                ('almoco', models.TextField(max_length=255)),
                ('merenda_tarde', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Segunda',
            },
        ),
        migrations.CreateModel(
            name='Segundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Segundo',
            },
        ),
        migrations.CreateModel(
            name='Setimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Setimo',
            },
        ),
        migrations.CreateModel(
            name='Sexta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merenda_manha', models.TextField(max_length=255)),
                ('almoco', models.TextField(max_length=255)),
                ('merenda_tarde', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Sexta',
            },
        ),
        migrations.CreateModel(
            name='Sexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Sexto',
            },
        ),
        migrations.CreateModel(
            name='Terca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merenda_manha', models.TextField(max_length=255)),
                ('almoco', models.TextField(max_length=255)),
                ('merenda_tarde', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Terça',
            },
        ),
        migrations.CreateModel(
            name='Terceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Terceiro',
            },
        ),
    ]
